version: "3.8"
services:

  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015

  backend:
    image: node:13-alpine
    command: node index.js
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - RETHINK_HOST=rethinkdb
      - RETHINK_PORT=28015
    ports:
      - 3001:3001

  frontend:
    image: node:13-alpine
    command: yarn dev
    working_dir: /app
    volumes:
      - ./frontend1:/app
    ports:
      - 3000:3000
      - 10000:10000
