version: "3.8"
services:

  rethinkdb:
    image: rethinkdb
    volumes:
      - /data/dnd/rethinkdb:/data

  s3:
    image: minio/minio
    command: server /data
    env_file: s3.env.prod
    volumes:
      - /data/dnd/s3:/data

  dnd-imageproxy:
    image: willnorris/imageproxy
    command: -addr 0.0.0.0:8081 -cache memory -cache /tmp/imageproxy -allowHosts s3

  dnd-app:
    image: dnd:latest
    command: yarn dev
    env_file: app.env.prod
    ports:
      - 3000:3000
